### ISSUE TITLE
Umbrella issue for application

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#413]
There are a number of issues known and waiting for time to be addressed:
- [x] apiserver for app handle need more logs #453 
- [x] chat api cache is not work. ( we need to watch all resource update, include application, llmchain, llm and so on, and then decide whether to deprecate the cache and reinit, otherwise will cause bug like #391) 
- [x] look like knowledgebaseretriever's doc score is always 0.(The documents taken from the vector database are right, but the score is always 0. This may be an upstream problem with langchaingo) fixed by https://github.com/tmc/langchaingo/pull/449
- [x] The sse in the chat api isn't really sse. The api should return the results in real time instead of pretending to be sse after getting all the results... fixed mainly by #415, some by #412 
- [x] #457
- [x] #458
- [x] #122

**Comment by nkwangleiGIT** [comment]
some of the items in the list can be covered in v0.1.0? I think we should keep most of them in v0.1.0

**Comment by Abirdcfly** [comment]
close this issue, chat issue(mainly in v0.3) will be track by #666
